# Generated by Django 2.2.7 on 2020-03-03 07:32

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200303_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', validators=[users.validators.profile_pic_size_limit]),
        ),
    ]
