# Generated by Django 2.2.7 on 2020-03-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalproduct',
            name='product_img1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='generalproduct',
            name='product_img2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
