# Generated by Django 2.2.7 on 2020-04-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200304_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalproduct',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
