# Generated by Django 2.2.7 on 2020-03-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
