# Generated by Django 2.2.7 on 2020-03-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_brand_brand_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='GeneralProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('brand', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Brand')),
                ('subcategory', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.SubCategory')),
            ],
        ),
    ]
