# Generated by Django 2.2.7 on 2020-03-03 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200303_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalproduct',
            name='brand',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Brand'),
        ),
        migrations.AlterField(
            model_name='generalproduct',
            name='subcategory',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.SubCategory'),
        ),
    ]
